# Generated by Django 5.2.3 on 2025-08-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_lancamento', models.DateField()),
                ('editora', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='autor.autor')),
            ],
            options={
                'db_table': 'tb_livro',
                'ordering': ['titulo'],
                'constraints': [models.UniqueConstraint(fields=('titulo', 'autor'), name='unique_titulo_autor')],
            },
        ),
    ]
