# Generated by Django 5.2.3 on 2025-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'editora',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='idx_editora_nome')],
            },
        ),
    ]
